apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 443              # External HTTPS port
      targetPort: 443