apiVersion: v1
kind: Service
metadata:
  name: globallydistributeddatabase
  namespace: financial
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080              # External HTTPS port
      targetPort: 8080